# vim:ft=ansible:
---
# This Playbook will install netdata

- name: git clone netdata
  git: repo=https://github.com/firehol/netdata.git depth=1 dest=/home/{{ user }}/netdata

- name: Get installation script 
  get_url: url=https://raw.githubusercontent.com/firehol/netdata-demo-site/master/install-required-packages.sh' dest=/tmp/kickstart.sh 

- name: Install dependencies 
  shell: ./tmp/kickstart.sh /home/{{ user }}/netdata/

- name: Install netdata 
  shell: ./netdata-installer.sh --dont-wait chdir=/home/{{ user }}/netdata/
  become: yes
