# vim:ft=ansible:
---
# This Playbook will install redis 

- name: Install jupyter by pip
  pip: name={{ item }} state=present
  become: yes
  with_items:
    - jupyter
    - notebook
    - ipywidgets
    - ipyparallel 

- name: Config jupyter server
  template: src=jupyter_notebook_config.j2 dest=/home/{{ user }}/.jupyter/jupyter_notebook_config.py

