# vim:ft=ansible:
---
# This Playbook will install redis 

- name: Install jupyter by pip
  pip: name={{ item }} state=present
  become: yes
  with_items:
    - jupyter
    - notebook
    - ipywidgets
    - ipyparallel 

- name: Generate Jupyter configuration
  shell: jupyter notebook --generate-config

- name: Update matplotlib fontList cache
  file: src=/home/{{ user }}/.cache/matplotlib/fontList.cache 
        state=absent
  ignore_errors: yes

- name: Config matplotlib
  template: src=matplotlibrc.j2 dest=/home/{{ user }}/.config/matplotlib/matplotlibrc
  ignore_errors: yes

- name: Config jupyter server
  template: src=jupyter_notebook_config.j2 dest=/home/{{ user }}/.jupyter/jupyter_notebook_config.py
  ignore_errors: yes

