# vim:ft=ansible:
---
# This Playbook will install all basic tools on all machines

- name: update the apt index
  apt: update_cache=yes cache_valid_time=3600
  become: yes

- name: Upgrade all packages
  apt: upgrade=dist
  become: yes

- name: build-essential
  apt: pkg=build-essential state=present update_cache=yes cache_valid_time=3600
  become: true

- name: Install basic tools
  apt: name={{ item }} update_cache=yes
  become: yes
  with_items:
    - language-pack-en
    - htop
    - exuberant-ctags
    - git
    - tree
    - vim

- name: Create the Downloads directory for all machines
  file: path=/home/ubuntu/Downloads state=directory mode=0755 owner=ubuntu
