# vim:ft=ansible:
---
# This Playbook install the latest Python

- name: Install python kits
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - python-pip
    - python-dev
  become: yes 

- name: Upgrade pip
  pip: name=pip extra_args=--upgrade
  become: yes
