# vim:ft=ansible:
---
# This Playbook install the latest tmux

- name: Add latest tmux repo
  apt_repository: repo='ppa:pi-rho/dev'
  
- name: Install tmux
  apt: name=tmux state=latest
  become: yes 

