# vim:ft=ansible:
---
# This Playbook will install redis 

- hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: Install redis-server
      apt: name=redis-server
      become: yes

    - name: Install redis-tools
      apt: name=redis-tools
      become: yes
